run:
  timeout: 2m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - revive
    - unused
    - gocritic
    - gosimple

issues:
  exclude-use-default: false

output:
  formats:
    - format: colored-line-number