version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: people_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U people_user"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      APP_PORT: ":8080"
      LOG_LEVEL: "info"
      DB_DSN: "postgres://people_user:secret@postgres:5432/people?sslmode=disable"
      AUTO_MIGRATE: "true"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  pgdata:
